"""Astrid-specific source-first DAG for the generic projection runtime."""

from __future__ import annotations

import sys

from .projection_types import ProjectionStep, command


def source_first_steps() -> tuple[ProjectionStep, ...]:
    python = sys.executable
    return (
        ProjectionStep(
            "addressing",
            (),
            (
                command(
                    python,
                    "scripts/introspection_addressing_audit.py",
                    "--workspace",
                    "{workspace}",
                    "--state-dir",
                    "{workspace}/diagnostics/introspection_addressing_v1",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("addressing",),
            ("introspections/introspection_*.txt",),
            (
                "diagnostics/introspection_addressing_v1/status.json",
                "diagnostics/introspection_addressing_v1/queue.md",
            ),
        ),
        ProjectionStep(
            "sandbox",
            ("addressing",),
            (
                command(
                    python,
                    "scripts/sandbox_trial_queue.py",
                    "--state-dir",
                    "{workspace}/diagnostics/sandbox_trial_queue_v1",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("addressing", "sandbox"),
            (
                "diagnostics/introspection_addressing_v1/status.json",
                "diagnostics/sandbox_trial_queue_v1/results/*.json",
            ),
            (
                "diagnostics/sandbox_trial_queue_v1/status.json",
                "diagnostics/sandbox_trial_queue_v1/queue.md",
            ),
        ),
        ProjectionStep(
            "corridor",
            ("addressing", "sandbox"),
            (
                command(
                    python,
                    "scripts/agency_corridor.py",
                    "--state-dir",
                    "{workspace}/diagnostics/agency_corridor_v1",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("addressing", "sandbox", "corridor_v1", "corridor_v2"),
            (
                "diagnostics/introspection_addressing_v1/status.json",
                "diagnostics/sandbox_trial_queue_v1/status.json",
            ),
            (
                "diagnostics/agency_corridor_v2/status.json",
                "diagnostics/agency_corridor_v2/leases.json",
                "diagnostics/agency_corridor_v2/queue.json",
                "diagnostics/agency_corridor_v2/programs.json",
                "diagnostics/agency_corridor_v2/report.md",
            ),
        ),
        ProjectionStep(
            "signal_spine",
            ("corridor",),
            (
                command(
                    python,
                    "scripts/signal_spine_projector.py",
                    "--workspace",
                    "{workspace}",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("signal_spine",),
            (
                "diagnostics/signal_spine_v1/journeys/*.json",
                "diagnostics/signal_spine_v1/temporal_associations/*.json",
                "diagnostics/signal_spine_v1/capture_gaps/*.json",
            ),
            (
                "diagnostics/signal_spine_v1/projection_status.json",
                "diagnostics/signal_spine_v1/report.md",
            ),
        ),
        ProjectionStep(
            "lived_state_witness",
            ("signal_spine",),
            (
                command(
                    python,
                    "scripts/lived_state_witness.py",
                    "--workspace",
                    "{workspace}",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("addressing", "signal_spine"),
            (
                "introspections/introspection_*.txt",
                "introspections/lived_state_witnesses/**/*.json",
                "environment_receipts/environment_receipts.jsonl",
                "../../../../neural-triple-reservoir/workspace/model_qos_receipts.jsonl",
            ),
            (
                "diagnostics/lived_state_witness_v1/status.json",
                "diagnostics/lived_state_witness_v1/witnesses.jsonl",
                "diagnostics/lived_state_witness_v1/auxiliary_artifacts.jsonl",
                "diagnostics/lived_state_witness_v1/gaps.jsonl",
                "diagnostics/lived_state_witness_v1/context_index.jsonl",
                "diagnostics/lived_state_witness_v1/report.md",
                "diagnostics/lived_state_witness_v1/migration_receipt.json",
            ),
        ),
        ProjectionStep(
            "claim_families",
            ("addressing", "signal_spine"),
            (
                command(
                    python,
                    "scripts/claim_families.py",
                    "--workspace",
                    "{workspace}",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("addressing", "claim_families"),
            (
                "diagnostics/introspection_addressing_v1/status.json",
                "environment_receipts/latest_environment_receipt.json",
            ),
            (
                "diagnostics/claim_families_v1/status.json",
                "diagnostics/claim_families_v1/report.md",
                "diagnostics/claim_families_v1/migration_receipt.json",
            ),
        ),
        ProjectionStep(
            "experiment_dossiers",
            ("sandbox", "claim_families"),
            (
                command(
                    python,
                    "scripts/experiment_dossiers.py",
                    "--workspace",
                    "{workspace}",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("sandbox", "claim_families"),
            (
                "diagnostics/sandbox_trial_queue_v1/status.json",
                "diagnostics/claim_families_v1/status.json",
                "diagnostics/lived_state_witness_v1/context_index.jsonl",
            ),
            (
                "diagnostics/experiment_dossiers_v1/status.json",
                "diagnostics/experiment_dossiers_v1/report.md",
            ),
        ),
        ProjectionStep(
            "authority_temporal",
            ("experiment_dossiers",),
            (
                command(
                    python,
                    "scripts/authority_temporal_audit.py",
                    "--workspace",
                    "{workspace}",
                    "--json",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("authority_lifecycle",),
            ("action_threads/threads/*/authority_gate.jsonl",),
            ("diagnostics/authority_temporal_v1/status.json",),
        ),
        ProjectionStep(
            "model_qos",
            ("authority_temporal",),
            (
                command(
                    python,
                    "scripts/model_qos_projector.py",
                    "--workspace",
                    "{workspace}",
                    "--json",
                    "project",
                    "--write",
                    "--receipt-json",
                ),
            ),
            ("model_qos",),
            (
                "../../../../neural-triple-reservoir/workspace/model_qos_receipts.jsonl",
            ),
            ("diagnostics/model_qos_v1/status.json",),
        ),
        ProjectionStep(
            "felt_contracts",
            (
                "experiment_dossiers",
                "corridor",
                "signal_spine",
                "lived_state_witness",
                "authority_temporal",
                "model_qos",
            ),
            (
                command(
                    python,
                    "scripts/felt_contract_graph.py",
                    "--workspace",
                    "{workspace}",
                    "project",
                    "--write",
                    "--actor",
                    "steward-control-projector",
                    "--receipt-json",
                    "--json",
                ),
            ),
            (
                "addressing",
                "sandbox",
                "corridor_v1",
                "corridor_v2",
                "signal_spine",
                "lived_state_witness",
                "claim_families",
                "authority_lifecycle",
                "model_qos",
                "felt_contracts",
            ),
            (
                "diagnostics/claim_families_v1/status.json",
                "diagnostics/experiment_dossiers_v1/status.json",
                "environment_receipts/environment_receipts.jsonl",
            ),
            (
                "diagnostics/felt_contract_graph_v1/status.json",
                "diagnostics/felt_contract_graph_v1/contracts.jsonl",
                "diagnostics/felt_contract_graph_v1/report.md",
                "diagnostics/felt_contract_graph_v1/migration_receipt.json",
            ),
        ),
    )
