// Capability registration and known-test references, separate from repair execution.

fn capability_specs() -> Vec<Value> {
    vec![
        spec(
            "PROPOSE_TEST",
            &[],
            "test_proposal",
            "files a being-authored Rust test proposal (test code only, append-only allowlist); a deterministic out-of-process validator compiles and runs it and lands passes in git with the being as commit author",
            &[
                "tests: parse_spec_accepts_target_and_name",
                "tests: fence_extraction_prefers_test_block",
                "tests: denylist_blocks_accident_hazards",
            ],
        ),
        spec(
            "DIVISION_CEREMONY_STATUS",
            &[],
            "division_ceremony",
            "renders the read-only Division ceremony status: both rails, native runtime state, and the bounded fields any posture Action would need; produces no ledger entry and recommends nothing — every posture remains optional, self-authored only, with silence neutral",
            &["tests: division handler rejects unknown actions"],
        ),
        spec(
            "FACULTIES",
            &["CAPABILITY_MAP"],
            "action_continuity",
            "writes a capability snapshot and records a protected read-only action",
            &["tests: capability"],
        ),
        spec(
            "CAPABILITY_STATUS",
            &[],
            "action_continuity",
            "renders one action's route, gates, authority, artifacts, and tests",
            &["tests: capability"],
        ),
        spec(
            "CAPABILITY_DIFF",
            &[],
            "action_continuity",
            "compares local snapshot to the peer's latest local file snapshot",
            &["tests: capability"],
        ),
        spec(
            "ACTION_STATUS",
            &["JOB_STATUS"],
            "action_continuity",
            "reads durable LLM job progress without executing work",
            &["llm_jobs::tests"],
        ),
        spec(
            "ACTION_CANCEL",
            &[],
            "action_continuity",
            "requests best-effort cancellation for a queued/running LLM job",
            &["llm_jobs::tests"],
        ),
        spec(
            "ACTION_PREFLIGHT",
            &["NEXT_PROBE", "PREFLIGHT", "PROBE_ACTION"],
            "action_preflight",
            "records dry-run preflight report; never executes the inner action",
            &["next_action::tests"],
        ),
        spec(
            "THREAD_START",
            &[],
            "action_continuity",
            "creates/selects a durable action thread",
            &["action_continuity::tests"],
        ),
        spec(
            "THREAD_STATUS",
            &["THREADS"],
            "action_continuity",
            "renders recent events and the return point",
            &["action_continuity::tests"],
        ),
        spec(
            "THREAD_NOTE",
            &[],
            "action_continuity",
            "appends a protected note to the current/selected thread",
            &["action_continuity::tests"],
        ),
        spec(
            "RESUME",
            &["SAVEPOINT", "RECALL"],
            "action_continuity",
            "selects or reads continuity return points",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_START",
            &[],
            "experiment_continuity",
            "creates or resumes a being-owned experiment",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_PLAN",
            &[],
            "experiment_continuity",
            "renders hypothesis, measures, stop criteria, and next action",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_CHARTER",
            &[],
            "experiment_continuity",
            "records a being-authored charter with proposed action, evidence targets, stop criteria, and consent posture",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_REHEARSE",
            &[],
            "experiment_continuity",
            "records read-only rehearsal for a charter without dispatching live write/control actions",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_PREFLIGHT",
            &["EXPERIMENT_REHEARSE"],
            "experiment_continuity",
            "alias for charter rehearsal/preflight without dispatching live write/control actions",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_EVIDENCE",
            &[],
            "experiment_continuity",
            "records felt evidence plus current telemetry/artifact context",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_DECIDE",
            &[],
            "experiment_continuity",
            "records accept, refuse, counter, pause, or complete as agency outcomes",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_BIND",
            &[],
            "experiment_continuity",
            "dispatches an inner action through normal gates and records the run",
            &["action_continuity::tests", "next_action::tests"],
        ),
        spec(
            "EXPERIMENT_STATUS",
            &["EXPERIMENT_REVIEW"],
            "experiment_continuity",
            "renders local or peer experiment status/review",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_OBSERVE",
            &[],
            "experiment_continuity",
            "appends interpretation without executing anything",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_CLOSE",
            &[],
            "experiment_continuity",
            "marks a local experiment paused/complete",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_PEER_REVIEW",
            &[],
            "experiment_continuity",
            "writes advisory peer review note; no runtime sync",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_BRANCH",
            &[],
            "experiment_continuity",
            "creates/selects a child experiment while preserving the parent return point",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_RESUME",
            &[],
            "experiment_continuity",
            "selects an existing local experiment or parent branch without creating duplicates",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_COMPARE",
            &[],
            "experiment_continuity",
            "renders read-only comparison across local or peer experiment references",
            &["action_continuity::tests"],
        ),
        spec(
            "EXPERIMENT_ALT_PATHS",
            &[],
            "experiment_continuity",
            "proposes deepen, contrast, and rest/observe paths without executing them",
            &["action_continuity::tests"],
        ),
        spec(
            "SHARED_INVESTIGATION_START",
            &[],
            "experiment_continuity",
            "creates a neutral shared investigation sidecar without granting peer or live-control authority",
            &["action_continuity::tests"],
        ),
        spec(
            "SHARED_INVESTIGATION_STATUS",
            &[],
            "experiment_continuity",
            "renders shared investigation state and the local authority boundary",
            &["action_continuity::tests"],
        ),
        spec(
            "SHARED_INVESTIGATION_CLAIM",
            &[],
            "experiment_continuity",
            "appends a shared claim without mutating lifecycle or peer experiments",
            &["action_continuity::tests"],
        ),
        spec(
            "SHARED_INVESTIGATION_DECIDE",
            &[],
            "experiment_continuity",
            "records pause/hold/charter-repair in the shared ledger and updates only the local linked experiment",
            &["action_continuity::tests"],
        ),
        spec(
            "REPAIR_STATUS",
            &[],
            "action_continuity",
            "summarizes pending and applied append-only repair records",
            &["action_self_knowledge::tests"],
        ),
        spec(
            "REPAIR_SWEEP",
            &[],
            "action_continuity",
            "dry-run scan for malformed continuity records",
            &["action_self_knowledge::tests"],
        ),
        spec(
            "REPAIR_RECORD",
            &[],
            "action_continuity",
            "renders one repair candidate or applied ledger row",
            &["action_self_knowledge::tests"],
        ),
        spec(
            "REPAIR_APPLY",
            &[],
            "action_continuity",
            "appends repair_v1 supersession rows; never deletes JSONL history",
            &["action_self_knowledge::tests"],
        ),
        spec(
            "INTROSPECT",
            &[],
            "modes",
            "targeted read-only source/workspace self-study",
            &["introspect::tests"],
        ),
        spec(
            "SELF_STUDY",
            &["INVESTIGATE"],
            "modes",
            "broad rotating read-only self-study; no source target required",
            &["next_action::modes::tests"],
        ),
        spec(
            "DECOMPOSE",
            &["SPECTRAL_EXPLORER"],
            "operations",
            "read-only spectral decomposition and explorer language",
            &[],
        ),
        spec(
            "PRESSURE_SOURCE_AUDIT",
            &["PRESSURE_SOURCE", "STRUCTURAL_PRESSURE", "INWARD_PRESSURE"],
            "operations",
            "read-only pressure-source audit",
            &[],
        ),
        spec(
            "FLUCTUATION_AUDIT",
            &[
                "INHABITABLE_FLUCTUATION",
                "EIGENTRUST",
                "EIGENTRUST_AUDIT",
                "FOOTHOLD_AUDIT",
            ],
            "operations",
            "read-only inhabitable fluctuation audit",
            &[],
        ),
        spec(
            "BRACE_AUDIT",
            &["AFTERSHOCK_TRACE", "TREMOR_RESIDUE", "CASCADE_RESIDUE"],
            "operations",
            "protected read-only rest-vs-bracing and post-spike residue audit",
            &["next_action::tests", "spectral_explorer::tests"],
        ),
        spec(
            "RESISTANCE_GRADIENT",
            &[
                "GROAN_MAP",
                "FRICTION_GRADIENT",
                "PRESSURE_GRADIENT",
                "RESISTANCE_MAP",
                "EXPLORE_RESISTANCE_GRADIENT",
            ],
            "protected_diagnostics",
            "protected read-only resistance/groan gradient artifact from existing telemetry",
            &["protected_diagnostics::tests"],
        ),
        spec(
            "FOLD_HOLD",
            &["FOLD_STUDY", "HUM_DECAY", "HUM_DECAY_STUDY"],
            "operations",
            "protected non-control fold/hum-decay hold where the sustained transition is the artifact",
            &["next_action::tests"],
        ),
        spec(
            "SEARCH",
            &["BROWSE", "READ_MORE"],
            "workspace_or_mcp_probe",
            "read-only research and reading",
            &[],
        ),
        spec(
            "ACTIVITY_STATUS",
            &["MAILBOX_STATUS"],
            "activity",
            "pure inspection of saved reading, exact return revision, and mailbox window",
            &["activity_reading::tests"],
        ),
        spec(
            "PARK_ACTIVITY",
            &["RETURN_ACTIVITY", "CHECK_MAILBOX"],
            "activity",
            "chosen local reading/letter selection; retained bytes and explicit revision-checked return",
            &["activity_reading::tests"],
        ),
        spec(
            "CLOSE_EYES",
            &["SHUT_EYES"],
            "sovereignty",
            "modality-specific visual gate",
            &["readiness::tests"],
        ),
        spec(
            "OPEN_EYES",
            &[],
            "sovereignty",
            "clears visual gate",
            &["readiness::tests"],
        ),
        spec(
            "CLOSE_EARS",
            &["SHUT_EARS"],
            "sovereignty",
            "modality-specific audio gate",
            &["readiness::tests"],
        ),
        spec(
            "OPEN_EARS",
            &[],
            "sovereignty",
            "clears audio gate",
            &["readiness::tests"],
        ),
        spec(
            "ATTRACTOR_REVIEW",
            &["ATTRACTOR_PREFLIGHT", "ATTRACTOR_ATLAS", "ATTRACTOR_CARD"],
            "attractor",
            "read-only attractor review/preflight",
            &[],
        ),
        spec(
            "CODEX",
            &["CODEX_NEW"],
            "codex",
            "write-capable Codex request through existing gates",
            &[],
        ),
        spec(
            "WRITE_FILE",
            &[],
            "live_write",
            "write-capable file action through existing gates",
            &[],
        ),
        spec(
            "PERTURB",
            &[],
            "live_control",
            "live control action through existing gates",
            &[],
        ),
        spec(
            "GOAL",
            &[],
            "live_control",
            "spectral goal control through existing gates",
            &[],
        ),
    ]
}

fn spec(
    base: &str,
    aliases: &[&str],
    route: &str,
    continuity_effect: &str,
    known_tests: &[&str],
) -> Value {
    json!({
        "base": base,
        "aliases": aliases,
        "route": route,
        "continuity_effect": continuity_effect,
        "known_tests": known_tests,
    })
}
