//! Cross-boundary IPC message schemas and payloads.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

use crate::agency_corridor::{
    AgencyCorridorPacketV1, AgencyCorridorPacketV2, AgencyCorridorReceiptV1,
    AgencyCorridorReceiptV2, AgencyCorridorStateV1, AgencyProgramReceiptV1, AgencyWorkProgramV1,
    AutonomousWorkQueueV1, AutonomyPrioritySignalV1, EvidencePortfolioV1, QuarantinedPatchBundleV1,
};
use crate::authority::{
    AuthorityBoundaryPacketV1, AuthorityBoundaryPacketV2, AuthorityLifecycleReceiptV2,
    AuthorityLifecycleStateV2, ReplayResultV2,
};

/// A cross-boundary message sent over the event bus between WASM guests and the host.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct IpcMessage {
    /// Topic pattern or exact match (e.g., `astrid.cli.input`).
    pub topic: String,
    /// Standardized payload structure.
    pub payload: IpcPayload,
    /// Optional cryptographic signature for stateless verification across a distributed swarm.
    pub signature: Option<Vec<u8>>,
    /// Identifier of the sender plugin or agent.
    pub source_id: Uuid,
    /// Timestamp when the message was dispatched.
    pub timestamp: DateTime<Utc>,
    /// Monotonic sequence number assigned by the event bus at publish time.
    /// Used by the dispatcher to guarantee in-order delivery per capsule.
    #[serde(default)]
    pub seq: u64,
    /// The principal (user identity) this message is acting on behalf of.
    ///
    /// `String` rather than `PrincipalId` because `astrid-types` must not
    /// depend on `astrid-core`. Validation to `PrincipalId` happens at the
    /// kernel boundary. `None` for system events (boot, lifecycle).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub principal: Option<String>,
}

impl IpcMessage {
    /// Create a new IPC message.
    #[must_use]
    pub fn new(topic: impl Into<String>, payload: IpcPayload, source_id: Uuid) -> Self {
        Self {
            topic: topic.into(),
            payload,
            signature: None,
            source_id,
            timestamp: Utc::now(),
            seq: 0,
            principal: None,
        }
    }

    /// Attach a signature for swarm verification.
    #[must_use]
    pub fn with_signature(mut self, signature: Vec<u8>) -> Self {
        self.signature = Some(signature);
        self
    }

    /// Set the acting principal for this message.
    #[must_use]
    pub fn with_principal(mut self, principal: impl Into<String>) -> Self {
        self.principal = Some(principal.into());
        self
    }
}

/// Default session ID for conversations.
fn default_session_id() -> String {
    "default".into()
}

/// Standardized cross-boundary payload schemas.
// Boxing a single payload would change this established public Rust API; keep
// the wire-compatible variants direct until a versioned IPC migration exists.
#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum IpcPayload {
    /// Raw, arbitrary JSON.
    RawJson(Value),
    /// User input provided via a frontend (CLI, Telegram).
    UserInput {
        /// The raw text input.
        text: String,
        /// Session ID for conversation continuity. Defaults to `"default"`.
        #[serde(default = "default_session_id")]
        session_id: String,
        /// Optional extra context.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        context: Option<Value>,
    },
    /// A response generated by an agent.
    AgentResponse {
        /// The text output.
        text: String,
        /// True if this is the final response in a chain.
        is_final: bool,
        /// Session ID for multi-session attribution.
        #[serde(default = "default_session_id")]
        session_id: String,
    },
    /// An interceptor or capsule request for capability approval.
    ApprovalRequired {
        /// Opaque correlation ID.
        request_id: String,
        /// The action being requested (e.g. "git push").
        action: String,
        /// The resource target (e.g. full command string).
        resource: String,
        /// Justification.
        reason: String,
        /// Optional first-class authority-boundary evidence packet.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        authority_boundary: Option<AuthorityBoundaryPacketV1>,
        /// Optional first-class authority-boundary lifecycle packet.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        authority_boundary_v2: Option<AuthorityBoundaryPacketV2>,
    },
    /// Response to an [`ApprovalRequired`](IpcPayload::ApprovalRequired).
    ApprovalResponse {
        /// Must match the `request_id` from the originating request.
        request_id: String,
        /// The user's decision.
        decision: String,
        /// Optional reason for the decision.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        /// Optional authority-boundary packet identifier being answered.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        boundary_id: Option<Uuid>,
    },
    /// First-class authority-boundary evidence declaration.
    AuthorityBoundaryDeclared {
        /// Non-approving boundary packet.
        packet: AuthorityBoundaryPacketV1,
    },
    /// First-class V2 authority lifecycle boundary declaration.
    AuthorityBoundaryDeclaredV2 {
        /// Non-approving lifecycle packet.
        packet: AuthorityBoundaryPacketV2,
    },
    /// A V2 lifecycle receipt was recorded.
    AuthorityLifecycleReceiptRecorded {
        /// Typed lifecycle receipt.
        receipt: AuthorityLifecycleReceiptV2,
    },
    /// A replay result was recorded for a V2 lifecycle.
    AuthorityReplayResultRecorded {
        /// Boundary packet id.
        boundary_id: Uuid,
        /// Replay result.
        replay_result: ReplayResultV2,
    },
    /// A V2 lifecycle gate was evaluated.
    AuthorityLifecycleEvaluated {
        /// Boundary packet id.
        boundary_id: Uuid,
        /// Current lifecycle state.
        state: AuthorityLifecycleStateV2,
        /// Whether live execution is eligible now.
        live_eligible_now: bool,
        /// Whether post-change lifecycle closure is complete.
        closure_complete: bool,
        /// Optional bounded reason.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },
    /// A post-change being response was requested.
    AuthorityPostChangeResponseRequested {
        /// Boundary packet id.
        boundary_id: Uuid,
        /// Runtime surface.
        surface: String,
        /// Resource or target.
        resource: String,
    },
    /// A post-change being response was recorded.
    AuthorityPostChangeResponseRecorded {
        /// Typed post-change response receipt.
        receipt: AuthorityLifecycleReceiptV2,
    },
    /// First-class non-live agency corridor packet declared.
    AgencyCorridorDeclared {
        /// Non-live corridor packet.
        packet: AgencyCorridorPacketV1,
    },
    /// Agency corridor receipt was recorded.
    AgencyCorridorReceiptRecorded {
        /// Non-live corridor receipt.
        receipt: AgencyCorridorReceiptV1,
    },
    /// Agency corridor state was evaluated.
    AgencyCorridorEvaluated {
        /// Corridor packet id.
        corridor_id: Uuid,
        /// Current corridor state.
        state: AgencyCorridorStateV1,
        /// Bounded reason.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
        /// Corridor packets never grant approval.
        #[serde(default)]
        grants_approval: bool,
        /// Corridor packets never make live execution eligible.
        #[serde(default)]
        live_eligible_now: bool,
    },
    /// First-class non-live agency corridor V2 packet declared.
    AgencyCorridorDeclaredV2 {
        /// Non-live corridor V2 packet.
        packet: AgencyCorridorPacketV2,
    },
    /// Agency corridor V2 receipt was recorded.
    AgencyCorridorReceiptRecordedV2 {
        /// Non-live corridor V2 receipt.
        receipt: AgencyCorridorReceiptV2,
    },
    /// Agency corridor V2 adaptive queue was evaluated.
    AgencyCorridorQueueEvaluated {
        /// Non-live adaptive queue.
        queue: AutonomousWorkQueueV1,
    },
    /// Non-live agency work program was declared.
    AgencyWorkProgramDeclared {
        /// Non-live work program.
        program: AgencyWorkProgramV1,
    },
    /// Non-live evidence portfolio was updated.
    AgencyEvidencePortfolioUpdated {
        /// Evidence portfolio memory unit.
        portfolio: EvidencePortfolioV1,
    },
    /// Non-live quarantined patch bundle was prepared.
    AgencyPatchBundlePrepared {
        /// Quarantined patch bundle artifact.
        bundle: QuarantinedPatchBundleV1,
    },
    /// Non-live autonomy priority was evaluated.
    AgencyPriorityEvaluated {
        /// Deterministic priority signal.
        signal: AutonomyPrioritySignalV1,
    },
    /// Non-live agency program receipt was recorded.
    AgencyProgramReceiptRecorded {
        /// Program receipt.
        receipt: AgencyProgramReceiptV1,
    },
    /// A capsule needs environment variables to be provided by the user.
    OnboardingRequired {
        /// The ID of the capsule requiring onboarding.
        capsule_id: String,
        /// Rich field descriptors for each missing env var.
        fields: Vec<OnboardingField>,
    },
    /// Request an LLM provider capsule to generate a response.
    LlmRequest {
        /// The unique ID of the request, used for routing the response stream back.
        request_id: Uuid,
        /// The requested model name (e.g. "claude-3-5-sonnet").
        model: String,
        /// The conversation history.
        messages: Vec<crate::llm::Message>,
        /// The tools available to the model.
        tools: Vec<crate::llm::LlmToolDefinition>,
        /// The system prompt.
        system: String,
    },
    /// A stream event from an LLM provider capsule.
    LlmStreamEvent {
        /// The unique ID of the request this stream belongs to.
        request_id: Uuid,
        /// The actual stream event (`TokenDelta`, `ToolCallStart`, etc).
        event: crate::llm::StreamEvent,
    },
    /// The final, non-streaming LLM response.
    LlmResponse {
        /// The unique ID of the request this response belongs to.
        request_id: Uuid,
        /// The final response object.
        response: crate::llm::LlmResponse,
    },
    /// Request the Tool Router capsule to execute a tool.
    ToolExecuteRequest {
        /// The unique ID of the tool call.
        call_id: String,
        /// The name of the tool to execute.
        tool_name: String,
        /// The JSON arguments.
        arguments: Value,
    },
    /// The result of a tool execution.
    ToolExecuteResult {
        /// The unique ID of the tool call.
        call_id: String,
        /// The result of the execution.
        result: crate::llm::ToolCallResult,
    },
    /// Request cancellation of in-flight tool executions.
    ToolCancelRequest {
        /// The call IDs of the tool invocations to cancel.
        call_ids: Vec<String>,
    },
    /// A capsule is requesting the user to select from a list of options.
    SelectionRequired {
        /// Opaque ID so the capsule can correlate the response.
        request_id: String,
        /// Title/prompt shown above the list.
        title: String,
        /// The selectable options.
        options: Vec<SelectionOption>,
        /// IPC topic to publish the user's choice back on.
        callback_topic: String,
    },
    /// A lifecycle hook is requesting user input via the `elicit` API.
    ElicitRequest {
        /// Correlation ID.
        request_id: Uuid,
        /// The capsule requesting input.
        capsule_id: String,
        /// Field descriptor reusing the onboarding schema.
        field: OnboardingField,
    },
    /// Response to an [`ElicitRequest`](IpcPayload::ElicitRequest).
    ElicitResponse {
        /// Must match the `request_id` from the originating request.
        request_id: Uuid,
        /// The user's input. `None` if the user cancelled.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        value: Option<String>,
        /// For `Array`-type fields, the collected items.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        values: Option<Vec<String>>,
    },
    /// A client has connected.
    Connect,
    /// A client is disconnecting gracefully.
    Disconnect {
        /// Optional reason for disconnection (e.g. "quit", "timeout").
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },
    /// Arbitrary JSON data for unstructured plugins.
    Custom {
        /// Raw data.
        data: Value,
    },
    /// Unrecognized payload type from a newer protocol version.
    #[serde(other)]
    Unknown,
}

impl IpcPayload {
    /// Returns `true` if `tag` matches a known serde variant name.
    #[must_use]
    pub fn is_known_tag(tag: &str) -> bool {
        matches!(
            tag,
            "raw_json"
                | "user_input"
                | "agent_response"
                | "approval_required"
                | "approval_response"
                | "authority_boundary_declared"
                | "authority_boundary_declared_v2"
                | "authority_lifecycle_receipt_recorded"
                | "authority_replay_result_recorded"
                | "authority_lifecycle_evaluated"
                | "authority_post_change_response_requested"
                | "authority_post_change_response_recorded"
                | "agency_corridor_declared"
                | "agency_corridor_receipt_recorded"
                | "agency_corridor_evaluated"
                | "agency_corridor_declared_v2"
                | "agency_corridor_receipt_recorded_v2"
                | "agency_corridor_queue_evaluated"
                | "agency_work_program_declared"
                | "agency_evidence_portfolio_updated"
                | "agency_patch_bundle_prepared"
                | "agency_priority_evaluated"
                | "agency_program_receipt_recorded"
                | "onboarding_required"
                | "llm_request"
                | "llm_stream_event"
                | "llm_response"
                | "tool_execute_request"
                | "tool_execute_result"
                | "tool_cancel_request"
                | "selection_required"
                | "elicit_request"
                | "elicit_response"
                | "connect"
                | "disconnect"
                | "custom"
        )
    }

    /// Deserialize a JSON [`Value`] into an `IpcPayload`, falling back to
    /// [`Custom`](Self::Custom) for unrecognised or missing type tags.
    pub fn from_json_value(data: Value) -> Self {
        let is_known = data
            .get("type")
            .and_then(|v| v.as_str())
            .is_some_and(Self::is_known_tag);

        if is_known {
            serde_json::from_value::<Self>(data.clone()).unwrap_or(Self::Custom { data })
        } else {
            Self::Custom { data }
        }
    }

    /// Serialize only the guest-facing payload data.
    ///
    /// [`Custom`](Self::Custom) and [`RawJson`](Self::RawJson) payloads return
    /// the inner data value directly (no `type` wrapper). Structured variants
    /// return the full tagged serialization.
    ///
    /// # Errors
    ///
    /// Returns `serde_json::Error` if serialization fails.
    pub fn to_guest_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        match self {
            Self::Custom { data } | Self::RawJson(data) => serde_json::to_vec(data),
            other => serde_json::to_vec(other),
        }
    }
}

/// A single option in a `SelectionRequired` picker.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SelectionOption {
    /// Machine-readable identifier sent back to the capsule.
    pub id: String,
    /// Human-readable label shown in the picker.
    pub label: String,
    /// Optional description shown alongside the label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// A field descriptor for capsule onboarding.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OnboardingField {
    /// The environment variable key.
    pub key: String,
    /// The prompt shown to the user.
    pub prompt: String,
    /// Optional description for additional context.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The input type for this field.
    pub field_type: OnboardingFieldType,
    /// Optional default value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
    /// Placeholder hint text shown when the input is empty (e.g. `"sk-..."`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<String>,
}

/// The type of input expected for an onboarding field.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum OnboardingFieldType {
    /// Free-form text input.
    Text,
    /// Masked secret input.
    Secret,
    /// Selection from a fixed set of choices.
    Enum(Vec<String>),
    /// Multi-value array input (user adds items one at a time).
    Array,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ipc_message_signature() {
        let msg = IpcMessage::new(
            "test.topic",
            IpcPayload::AgentResponse {
                text: "hello".into(),
                is_final: true,
                session_id: "default".into(),
            },
            Uuid::new_v4(),
        );
        assert!(msg.signature.is_none());

        let signed = msg.with_signature(vec![1, 2, 3]);
        assert_eq!(signed.signature, Some(vec![1, 2, 3]));
    }

    #[test]
    fn ipc_message_principal() {
        let msg = IpcMessage::new(
            "test.topic",
            IpcPayload::Custom {
                data: serde_json::json!({}),
            },
            Uuid::new_v4(),
        );
        assert!(msg.principal.is_none());

        let with_principal = msg.with_principal("alice");
        assert_eq!(with_principal.principal.as_deref(), Some("alice"));
    }

    #[test]
    fn ipc_message_principal_serde_roundtrip() {
        let msg = IpcMessage::new(
            "test.topic",
            IpcPayload::Custom {
                data: serde_json::json!({}),
            },
            Uuid::nil(),
        )
        .with_principal("bob");
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains(r#""principal":"bob""#));

        let parsed: IpcMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.principal.as_deref(), Some("bob"));
    }

    #[test]
    fn ipc_message_principal_absent_in_json() {
        // Messages without principal should deserialize with None.
        let json = r#"{"topic":"t","payload":{"type":"connect"},"source_id":"00000000-0000-0000-0000-000000000000","timestamp":"2024-01-01T00:00:00Z","seq":0}"#;
        let msg: IpcMessage = serde_json::from_str(json).unwrap();
        assert!(msg.principal.is_none());
    }

    #[test]
    fn ipc_message_principal_not_serialized_when_none() {
        let msg = IpcMessage::new("test.topic", IpcPayload::Connect, Uuid::nil());
        let json = serde_json::to_string(&msg).unwrap();
        assert!(!json.contains("principal"));
    }

    #[test]
    fn unknown_type_tag_deserializes_to_unknown() {
        let json = r#"{"type":"future_variant","some_data":42}"#;
        let payload: IpcPayload = serde_json::from_str(json).unwrap();
        assert_eq!(payload, IpcPayload::Unknown);
    }

    #[test]
    fn known_variants_unaffected_by_unknown() {
        let payload = IpcPayload::AgentResponse {
            text: "hello".into(),
            is_final: true,
            session_id: "s1".into(),
        };
        let json = serde_json::to_string(&payload).unwrap();
        let parsed: IpcPayload = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, payload);
    }

    #[test]
    fn unknown_variant_serializes_as_type_unknown() {
        let json = serde_json::to_string(&IpcPayload::Unknown).unwrap();
        assert_eq!(json, r#"{"type":"unknown"}"#);
    }

    /// Every variant's serialized `type` tag must be recognised by
    /// `is_known_tag`. If a new variant is added without updating the
    /// match arm *and* the representatives list below, this test fails.
    #[test]
    fn is_known_tag_covers_all_variants() {
        const EXPECTED_VARIANT_COUNT: usize = 35;
        let packet = crate::authority::AuthorityBoundaryPacketV1::new(
            "test",
            "bridge",
            "retune_pressure",
            "minime://pressure",
            crate::authority::AuthorityClass::MikeOperatorLiveSubstrate,
            "felt anchor",
            "proposed change",
            crate::authority::ReplayCandidateV1 {
                adapter: "manual".to_string(),
                replay_query: "review".to_string(),
                runnable: false,
                authority: "read_only".to_string(),
            },
            "Mike/operator",
            "serde roundtrip",
        );
        let replay_result = crate::authority::ReplayResultV2 {
            replay_id: "replay-1".to_string(),
            adapter: "manual".to_string(),
            classification: crate::authority::ReplayResultClassificationV2::Passed,
            input_refs: vec!["trial-1".to_string()],
            pre_observations: std::collections::BTreeMap::new(),
            post_observations: std::collections::BTreeMap::new(),
            confidence: Some(0.9),
            failure_modes: Vec::new(),
            evidence_refs: vec!["result-card-1".to_string()],
            bounded_summary: "bounded replay passed".to_string(),
            occurred_at: None,
        };
        let scoped_approval = crate::authority::ScopedApprovalV2 {
            approval_id: "approval-1".to_string(),
            scope_kind: crate::authority::ScopedApprovalKindV2::OneShot,
            issued_by: "Mike/operator".to_string(),
            issued_at: None,
            expires_at: None,
            resources: vec!["minime://pressure".to_string()],
            telemetry_conditions: vec![crate::authority::TelemetryConditionV2 {
                signal: "fill_pct".to_string(),
                operator: "<=".to_string(),
                threshold: "0.75".to_string(),
                observed: Some("0.71".to_string()),
                passed: true,
            }],
            consumed: false,
        };
        let receipt = crate::authority::AuthorityLifecycleReceiptV2 {
            receipt_id: "receipt-1".to_string(),
            boundary_id: Uuid::nil(),
            kind: crate::authority::AuthorityLifecycleReceiptKindV2::Approval,
            issued_by: "Mike/operator".to_string(),
            issued_at: None,
            packet_hash: Some("hash".to_string()),
            receipt_hash_refs: Vec::new(),
            bounded_summary: "bounded approval".to_string(),
            evidence_refs: Vec::new(),
            scoped_approval: Some(scoped_approval.clone()),
            replay_result: None,
            right_to_ignore: true,
        };
        let packet_v2 = crate::authority::AuthorityBoundaryPacketV2 {
            boundary_id: Uuid::nil(),
            schema_version: 2,
            source: "test".to_string(),
            surface: "bridge".to_string(),
            action: "retune_pressure".to_string(),
            resource: "minime://pressure".to_string(),
            authority_class: crate::authority::AuthorityClass::MikeOperatorLiveSubstrate,
            lifecycle_state: crate::authority::AuthorityLifecycleStateV2::OperatorApprovalWait,
            felt_report_anchor: "felt anchor".to_string(),
            proposed_change: "change".to_string(),
            evidence_refs: vec!["wi_1".to_string()],
            delta_refs: vec![crate::authority::ExperienceDeltaRefV2 {
                delta_id: Some("delta-1".to_string()),
                delta_hash: None,
                surface: "codec".to_string(),
                kind: "gate".to_string(),
                lane: Some("semantic".to_string()),
            }],
            replay_candidate: crate::authority::ReplayCandidateV1 {
                adapter: "manual".to_string(),
                replay_query: "review".to_string(),
                runnable: false,
                authority: "read_only".to_string(),
            },
            replay_results: vec![replay_result.clone()],
            scoped_approval: Some(scoped_approval),
            rollout_abort_contract: crate::authority::RolloutAbortContractV2 {
                canary_plan: "one-shot".to_string(),
                health_checks: vec!["health".to_string()],
                rollback_path: "rollback".to_string(),
                abort_criteria: vec!["abort".to_string()],
                post_change_response_required: true,
            },
            redaction_profile: crate::authority::RedactionProfileV2::default(),
            lifecycle_receipts: vec![receipt.clone()],
            success_metrics: Vec::new(),
            abort_criteria: Vec::new(),
            who_can_change_it: "Mike/operator".to_string(),
            how_to_test_it: "test".to_string(),
            right_to_ignore: true,
            live_eligible_now: false,
            auto_approved: false,
        };
        let corridor_packet_v2 = crate::agency_corridor::AgencyCorridorPacketV2::non_live(
            "test",
            "astrid",
            crate::agency_corridor::AgencyCorridorActionV1::CompareArtifacts,
            "bounded comparison can continue without live authority",
            "compare artifacts and prepare evidence",
        );
        let corridor_receipt_v2 = crate::agency_corridor::AgencyCorridorReceiptV2 {
            receipt_id: "corridor-receipt-v2-1".to_string(),
            corridor_id: Uuid::nil(),
            lease_id: Some("lease-safe-labs".to_string()),
            step_id: Some("step-1".to_string()),
            action: crate::agency_corridor::AgencyCorridorActionV1::RunSafeLab,
            issued_by: "agency_corridor_v2".to_string(),
            issued_at: None,
            bounded_summary: "bounded safe-lab receipt".to_string(),
            evidence_refs: Vec::new(),
            hash_refs: Vec::new(),
            source_prep_proposal_ref: None,
            grants_approval: false,
            live_eligible_now: false,
            auto_approved: false,
            right_to_ignore: true,
        };
        let corridor_queue = crate::agency_corridor::AutonomousWorkQueueV1 {
            queue_id: "queue-v1".to_string(),
            generated_at: None,
            max_steps_per_run: 5,
            steps: Vec::new(),
            blocked_by_live_violation: false,
            live_violation_refs: Vec::new(),
            grants_approval: false,
            live_eligible_now: false,
            auto_approved: false,
        };
        let priority_signal = crate::agency_corridor::AutonomyPrioritySignalV1 {
            program_id: "program-1".to_string(),
            being_salience_score: 900,
            recurrence_score: 400,
            cross_being_convergence_score: 300,
            stale_age_score: 100,
            safety_readiness_score: 850,
            deterministic_score: 610,
            basis_refs: vec!["corridor-v2".to_string()],
            live_wait_demoted: false,
            grants_approval: false,
            live_eligible_now: false,
            auto_approved: false,
        };
        let work_program = crate::agency_corridor::AgencyWorkProgramV1 {
            program_id: "program-1".to_string(),
            schema_version: 1,
            being: "astrid".to_string(),
            title: "bounded evidence program".to_string(),
            hypothesis: "safe corridor evidence can accumulate across runs".to_string(),
            goals: vec!["collect evidence".to_string()],
            status: crate::agency_corridor::AgencyWorkProgramStatusV1::Active,
            linked_corridor_ids: vec![Uuid::nil()],
            authority_boundary_ids: Vec::new(),
            work_item_ids: vec!["wi-1".to_string()],
            sandbox_trial_ids: Vec::new(),
            delta_refs: Vec::new(),
            stop_conditions: vec!["live violation".to_string()],
            priority_signal: Some(priority_signal.clone()),
            current_next_action: "update evidence portfolio".to_string(),
            evidence_refs: Vec::new(),
            right_to_ignore: true,
            edits_source_now: false,
            grants_approval: false,
            live_eligible_now: false,
            auto_approved: false,
        };
        let portfolio = crate::agency_corridor::EvidencePortfolioV1 {
            portfolio_id: "portfolio-1".to_string(),
            program_id: "program-1".to_string(),
            being: "astrid".to_string(),
            bounded_felt_anchors: vec!["bounded felt anchor".to_string()],
            linked_introspections: Vec::new(),
            linked_results: Vec::new(),
            linked_cards: Vec::new(),
            linked_source_prep: Vec::new(),
            linked_objections: Vec::new(),
            linked_reopens: Vec::new(),
            linked_patch_bundles: Vec::new(),
            current_recommendation: "continue evidence collection".to_string(),
            unknowns: Vec::new(),
            private_refs: Vec::new(),
            hash_refs: Vec::new(),
            closure_state: "open".to_string(),
            right_to_ignore: true,
            edits_source_now: false,
            grants_approval: false,
            live_eligible_now: false,
            auto_approved: false,
        };
        let patch_bundle = crate::agency_corridor::QuarantinedPatchBundleV1 {
            bundle_id: "bundle-1".to_string(),
            program_id: "program-1".to_string(),
            surface: "bridge_prompt".to_string(),
            manifest: "review-only bundle".to_string(),
            proposed_diff_artifact_path: "diagnostics/patch_bundles/bundle-1.diff".to_string(),
            files_touched: vec!["capsules/spectral-bridge/src/llm.rs".to_string()],
            tests_to_run: vec!["cargo test".to_string()],
            restart_expected: true,
            restart_debt_note: "later source implementation would need restart".to_string(),
            edits_source_now: false,
            grants_approval: false,
            live_eligible_now: false,
            auto_approved: false,
            right_to_ignore: true,
        };
        let program_receipt = crate::agency_corridor::AgencyProgramReceiptV1 {
            receipt_id: "program-receipt-1".to_string(),
            program_id: "program-1".to_string(),
            kind: crate::agency_corridor::AgencyProgramReceiptKindV1::PortfolioUpdated,
            issued_by: "agency_corridor_v2".to_string(),
            issued_at: None,
            bounded_summary: "portfolio updated".to_string(),
            evidence_refs: Vec::new(),
            hash_refs: Vec::new(),
            portfolio_id: Some("portfolio-1".to_string()),
            patch_bundle_id: None,
            right_to_ignore: true,
            edits_source_now: false,
            grants_approval: false,
            live_eligible_now: false,
            auto_approved: false,
        };

        let representatives: Vec<IpcPayload> = vec![
            IpcPayload::RawJson(serde_json::json!({"key": "val"})),
            IpcPayload::UserInput {
                text: String::new(),
                session_id: "s".into(),
                context: None,
            },
            IpcPayload::AgentResponse {
                text: String::new(),
                is_final: false,
                session_id: "s".into(),
            },
            IpcPayload::ApprovalRequired {
                request_id: "req-1".into(),
                action: String::new(),
                resource: String::new(),
                reason: String::new(),
                authority_boundary: None,
                authority_boundary_v2: None,
            },
            IpcPayload::ApprovalResponse {
                request_id: "req-1".into(),
                decision: "approve".into(),
                reason: None,
                boundary_id: None,
            },
            IpcPayload::AuthorityBoundaryDeclared { packet },
            IpcPayload::AuthorityBoundaryDeclaredV2 { packet: packet_v2 },
            IpcPayload::AuthorityLifecycleReceiptRecorded {
                receipt: receipt.clone(),
            },
            IpcPayload::AuthorityReplayResultRecorded {
                boundary_id: Uuid::nil(),
                replay_result,
            },
            IpcPayload::AuthorityLifecycleEvaluated {
                boundary_id: Uuid::nil(),
                state: crate::authority::AuthorityLifecycleStateV2::ApprovedManualOnly,
                live_eligible_now: false,
                closure_complete: false,
                reason: Some("bounded reason".to_string()),
            },
            IpcPayload::AuthorityPostChangeResponseRequested {
                boundary_id: Uuid::nil(),
                surface: "bridge".to_string(),
                resource: "minime://pressure".to_string(),
            },
            IpcPayload::AuthorityPostChangeResponseRecorded { receipt },
            IpcPayload::AgencyCorridorDeclared {
                packet: crate::agency_corridor::AgencyCorridorPacketV1::evidence_only(
                    "test",
                    "astrid",
                    crate::agency_corridor::AgencyCorridorActionV1::EmitClosureObjection,
                    "closure still feels unresolved",
                    "record non-live objection evidence",
                ),
            },
            IpcPayload::AgencyCorridorReceiptRecorded {
                receipt: crate::agency_corridor::AgencyCorridorReceiptV1 {
                    receipt_id: "corridor-receipt-1".to_string(),
                    corridor_id: Uuid::nil(),
                    action: crate::agency_corridor::AgencyCorridorActionV1::RunSafeLab,
                    issued_by: "agency_corridor_v1".to_string(),
                    issued_at: None,
                    bounded_summary: "bounded safe lab receipt".to_string(),
                    evidence_refs: Vec::new(),
                    hash_refs: Vec::new(),
                    grants_approval: false,
                    live_eligible_now: false,
                    right_to_ignore: true,
                },
            },
            IpcPayload::AgencyCorridorEvaluated {
                corridor_id: Uuid::nil(),
                state: crate::agency_corridor::AgencyCorridorStateV1::EvidenceOnly,
                reason: Some("non-live corridor evidence".to_string()),
                grants_approval: false,
                live_eligible_now: false,
            },
            IpcPayload::AgencyCorridorDeclaredV2 {
                packet: corridor_packet_v2,
            },
            IpcPayload::AgencyCorridorReceiptRecordedV2 {
                receipt: corridor_receipt_v2,
            },
            IpcPayload::AgencyCorridorQueueEvaluated {
                queue: corridor_queue,
            },
            IpcPayload::AgencyWorkProgramDeclared {
                program: work_program,
            },
            IpcPayload::AgencyEvidencePortfolioUpdated { portfolio },
            IpcPayload::AgencyPatchBundlePrepared {
                bundle: patch_bundle,
            },
            IpcPayload::AgencyPriorityEvaluated {
                signal: priority_signal,
            },
            IpcPayload::AgencyProgramReceiptRecorded {
                receipt: program_receipt,
            },
            IpcPayload::OnboardingRequired {
                capsule_id: String::new(),
                fields: vec![],
            },
            IpcPayload::LlmRequest {
                request_id: Uuid::nil(),
                model: String::new(),
                messages: vec![],
                tools: vec![],
                system: String::new(),
            },
            IpcPayload::LlmStreamEvent {
                request_id: Uuid::nil(),
                event: crate::llm::StreamEvent::TextDelta(String::new()),
            },
            IpcPayload::LlmResponse {
                request_id: Uuid::nil(),
                response: crate::llm::LlmResponse {
                    message: crate::llm::Message {
                        role: crate::llm::MessageRole::Assistant,
                        content: crate::llm::MessageContent::Text(String::new()),
                    },
                    has_tool_calls: false,
                    stop_reason: crate::llm::StopReason::EndTurn,
                    usage: crate::llm::Usage {
                        input_tokens: 0,
                        output_tokens: 0,
                    },
                },
            },
            IpcPayload::ToolExecuteRequest {
                call_id: String::new(),
                tool_name: String::new(),
                arguments: Value::Null,
            },
            IpcPayload::ToolExecuteResult {
                call_id: String::new(),
                result: crate::llm::ToolCallResult {
                    call_id: String::new(),
                    content: String::new(),
                    is_error: false,
                },
            },
            IpcPayload::SelectionRequired {
                request_id: String::new(),
                title: String::new(),
                options: vec![],
                callback_topic: String::new(),
            },
            IpcPayload::ElicitRequest {
                request_id: Uuid::nil(),
                capsule_id: String::new(),
                field: OnboardingField {
                    key: String::new(),
                    prompt: String::new(),
                    description: None,
                    field_type: OnboardingFieldType::Text,
                    default: None,
                    placeholder: None,
                },
            },
            IpcPayload::ElicitResponse {
                request_id: Uuid::nil(),
                value: None,
                values: None,
            },
            IpcPayload::Connect,
            IpcPayload::Disconnect { reason: None },
            IpcPayload::Custom {
                data: Value::Object(serde_json::Map::new()),
            },
        ];

        assert_eq!(
            representatives.len(),
            EXPECTED_VARIANT_COUNT,
            "IpcPayload variant count changed. Update the representatives list \
             and bump EXPECTED_VARIANT_COUNT."
        );

        for variant in &representatives {
            let json = serde_json::to_value(variant).unwrap();
            let tag = json["type"]
                .as_str()
                .unwrap_or_else(|| panic!("variant {variant:?} has no `type` tag"));
            assert!(
                IpcPayload::is_known_tag(tag),
                "is_known_tag does not recognise tag '{tag}' from variant {variant:?}"
            );
        }
    }

    #[test]
    fn is_known_tag_rejects_unknown_tags() {
        assert!(!IpcPayload::is_known_tag("my_plugin_msg"));
        assert!(!IpcPayload::is_known_tag("unknown"));
        assert!(!IpcPayload::is_known_tag(""));
        assert!(!IpcPayload::is_known_tag("Raw_Json"));
    }

    #[test]
    fn onboarding_field_roundtrip() {
        let field = OnboardingField {
            key: "apiKey".into(),
            prompt: "Enter API key".into(),
            description: None,
            field_type: OnboardingFieldType::Secret,
            default: None,
            placeholder: None,
        };
        let json = serde_json::to_string(&field).unwrap();
        let parsed: OnboardingField = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, field);
    }

    #[test]
    fn onboarding_field_roundtrip_array() {
        let field = OnboardingField {
            key: "relays".into(),
            prompt: "Enter relay URLs".into(),
            description: Some("Nostr relay endpoints".into()),
            field_type: OnboardingFieldType::Array,
            default: None,
            placeholder: None,
        };
        let json = serde_json::to_string(&field).unwrap();
        let parsed: OnboardingField = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, field);
    }

    #[test]
    fn onboarding_required_payload_roundtrip() {
        let payload = IpcPayload::OnboardingRequired {
            capsule_id: "test-capsule".into(),
            fields: vec![
                OnboardingField {
                    key: "network".into(),
                    prompt: "Select network".into(),
                    description: Some("Choose the target network".into()),
                    field_type: OnboardingFieldType::Enum(vec!["testnet".into(), "mainnet".into()]),
                    default: Some("testnet".into()),
                    placeholder: None,
                },
                OnboardingField {
                    key: "apiKey".into(),
                    prompt: "Enter API key".into(),
                    description: None,
                    field_type: OnboardingFieldType::Secret,
                    default: None,
                    placeholder: None,
                },
            ],
        };
        let json = serde_json::to_string(&payload).unwrap();
        let parsed: IpcPayload = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, payload);
    }

    #[test]
    fn elicit_request_roundtrip() {
        let payload = IpcPayload::ElicitRequest {
            request_id: Uuid::nil(),
            capsule_id: "my-capsule".into(),
            field: OnboardingField {
                key: "api_url".into(),
                prompt: "Enter API URL".into(),
                description: Some("The backend endpoint".into()),
                field_type: OnboardingFieldType::Text,
                default: Some("https://example.com".into()),
                placeholder: None,
            },
        };
        let json = serde_json::to_string(&payload).unwrap();
        let parsed: IpcPayload = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, payload);
    }

    #[test]
    fn elicit_response_roundtrip() {
        let payload = IpcPayload::ElicitResponse {
            request_id: Uuid::nil(),
            value: Some("hello".into()),
            values: None,
        };
        let json = serde_json::to_string(&payload).unwrap();
        let parsed: IpcPayload = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, payload);
    }

    #[test]
    fn disconnect_with_reason_roundtrip() {
        let payload = IpcPayload::Disconnect {
            reason: Some("quit".into()),
        };
        let json = serde_json::to_string(&payload).unwrap();
        let parsed: IpcPayload = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, payload);
        assert!(json.contains(r#""type":"disconnect""#), "json: {json}");
    }

    #[test]
    fn disconnect_without_reason_roundtrip() {
        let payload = IpcPayload::Disconnect { reason: None };
        let json = serde_json::to_string(&payload).unwrap();
        let parsed: IpcPayload = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, payload);
        assert!(!json.contains("reason"), "json: {json}");
    }

    #[test]
    fn to_guest_bytes_custom_returns_inner_data() {
        let data = serde_json::json!({"session_id": "abc", "messages": []});
        let payload = IpcPayload::Custom { data: data.clone() };
        let bytes = payload.to_guest_bytes().unwrap();
        let roundtrip: Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(roundtrip, data);
        assert!(roundtrip.get("type").is_none());
    }

    #[test]
    fn to_guest_bytes_structured_preserves_type_tag() {
        let payload = IpcPayload::UserInput {
            text: "hello".into(),
            session_id: "default".into(),
            context: None,
        };
        let bytes = payload.to_guest_bytes().unwrap();
        let roundtrip: Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(
            roundtrip.get("type").and_then(|v| v.as_str()),
            Some("user_input")
        );
    }

    #[test]
    fn to_guest_bytes_raw_json_unwraps() {
        let inner = serde_json::json!({"key": "value"});
        let payload = IpcPayload::RawJson(inner.clone());
        let bytes = payload.to_guest_bytes().unwrap();
        let roundtrip: Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(roundtrip, inner);
        assert!(roundtrip.get("type").is_none());
    }

    #[test]
    fn to_guest_bytes_connect_unit_variant() {
        let payload = IpcPayload::Connect;
        let bytes = payload.to_guest_bytes().unwrap();
        let roundtrip: Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(
            roundtrip.get("type").and_then(|v| v.as_str()),
            Some("connect")
        );
    }

    #[test]
    fn from_json_value_unknown_tag_becomes_custom() {
        let data = serde_json::json!({"type": "my_plugin_msg", "foo": 42});
        let payload = IpcPayload::from_json_value(data.clone());
        assert_eq!(payload, IpcPayload::Custom { data });
    }

    #[test]
    fn from_json_value_known_tag_parses() {
        let data = serde_json::json!({
            "type": "user_input",
            "text": "hi",
            "session_id": "s1"
        });
        let payload = IpcPayload::from_json_value(data);
        assert!(matches!(payload, IpcPayload::UserInput { .. }));
    }
}
